on:
  push:
    branches:
      - main
  
name: Deploy code to Windows Virtual Machine dsbapp0103

jobs:
  remote-git-pull:
    runs-on: dsb_win
    steps:
      - name: git clone and pull on remote desktop dsbapp0103
        shell: pwsh
        run: |
            Enter-PSSession dsbapp0103 -Credential DSB\THSL0312
            cd C:\Users\THSL0312\Documents
            git clone git@github.com:databricks/mlops-stack.git
            git pull git@github.com:databricks/mlops-stack.git
